[[tasks]]
priority = 1
time = 1200

[[tasks]]
priority = 0
time = 45

[[tasks]]
priority = 2
time = 8900

[[tasks]]
priority = 1
time = 150

[[tasks]]
priority = 3
time = 60000

[[tasks]]
priority = 0
time = 10

[[tasks]]
priority = 1
time = 300

[[tasks]]
priority = 2
time = 4500

[[tasks]]
priority = 1
time = 800

[[tasks]]
priority = 0
time = 25

[[tasks]]
priority = 1
time = 1100

[[tasks]]
priority = 2
time = 3200

[[tasks]]
priority = 0
time = 15

[[tasks]]
priority = 3
time = 120000

[[tasks]]
priority = 1
time = 500

[[tasks]]
priority = 0
time = 60

[[tasks]]
priority = 1
time = 900

[[tasks]]
priority = 2
time = 7000

[[tasks]]
priority = 1
time = 250

[[tasks]]
priority = 0
time = 5

[[tasks]]
priority = 1
time = 1350

[[tasks]]
priority = 1
time = 1350

[[tasks]]
priority = 0
time = 100

[[tasks]]
priority = 2
time = 15000

[[tasks]]
priority = 1
time = 400

[[tasks]]
priority = 3
time = 300000

[[tasks]]
priority = 1
time = 600

[[tasks]]
priority = 0
time = 30

[[tasks]]
priority = 2
time = 5500

[[tasks]]
priority = 1
time = 120

[[tasks]]
priority = 1
time = 880

[[tasks]]
priority = 0
time = 50

[[tasks]]
priority = 2
time = 9900

[[tasks]]
priority = 1
time = 440

[[tasks]]
priority = 3
time = 45000

[[tasks]]
priority = 0
time = 8

[[tasks]]
priority = 0
time = 8

[[tasks]]
priority = 1
time = 1100

[[tasks]]
priority = 2
time = 6200

[[tasks]]
priority = 1
time = 350

[[tasks]]
priority = 0
time = 20

[[tasks]]
priority = 3
time = 88888

[[tasks]]
priority = 1
time = 1500

[[tasks]]
priority = 2
time = 4200

[[tasks]]
priority = 0
time = 55

[[tasks]]
priority = 1
time = 900

[[tasks]]
priority = 2
time = 11000

[[tasks]]
priority = 1
time = 200

[[tasks]]
priority = 0
time = 15

[[tasks]]
priority = 3
time = 500000